type: pipeline_job

compute:
  target: azureml:ManojCluster

jobs:
  hello_world_component_1:
    type: component_job
    compute:
      target: azureml:ManojCluster
    component: file:./helloworld_component_python.yml
    inputs:
      sample_data:
        data: 
          datastore: azureml:workspaceblobstore
          path: az-ml-artifacts/3c233acc7a166896202ebe35aedc2e13/data
      sample_string: hello python world

