type: pipeline_job

compute:
  target: azureml:ManojCluster

jobs:
  hello_world_component_1:
    type: component_job
    compute:
      target: azureml:ManojCluster
    component: file:../components/helloworld_component_python.yml

