type: pipeline_job

name: simplePipelineJobWithComponentOutput
display_name: PipelineJobHelloWorldWithComponentOutput
description: The hello world pipeline job with component output
tags:
  tag: tagvalue
  owner: sdkteam

compute:
  target: azureml:cpu-cluster

inputs:
  # examples of inputs that take values such as int, string, etc.
  job_in_number: 10
  job_in_path:
    data:
      local_path: ../data
      datastore: azureml:workspaceblobstore
    mode: mount

#defaults:
#  component_job:
#    datastore: azureml:workspaceblobstore

jobs:
  hello_world_component_1:
    type: component_job
    compute:
      target: azureml:cpu_cluster
    inputs:
      component_in_number: inputs.job_in_number
      component_in_path: inputs.job_in_path
    outputs:
      component_out_path:
        data:
          datastore: azureml:workspaceblobstore
          path: /hello_world_component_1_output
        mode: mount

    component: file:../components/helloworld_component_with_input_and_output.yml

  hello_world_component_2:
    type: component_job
    compute:
      target: azureml:cpu_cluster
    inputs:
      component_in_number: inputs.job_in_number
      component_in_path: inputs.job_in_path
    outputs:
      component_out_path:
        data:
          path: /hello_world_component_2_output
        mode: mount

    component: file:../components/helloworld_component_with_input_and_output.yml

  merge_component_outputs:
    type: component_job
    compute:
      target: azureml:cpu_cluster
    inputs:
      component_in_number: inputs.job_in_number
      component_in_path_1: jobs.hello_world_component_1.outputs.component_out_path
      component_in_path_2: jobs.hello_world_component_2.outputs.component_out_path

    component:
      command: >-
        echo Hello World &&
        echo {inputs.component_in_number} &&
        mkdir -p {outputs.component_out_path_1} &&
        mkdir -p {outputs.component_out_path_2} &&
        cp -p -r {inputs.component_in_path_1} {outputs.component_out_path_1} &&
        cp -p -r {inputs.component_in_path_2} {outputs.component_out_path_2}
      environment: azureml:AzureML-Minimal:1
      inputs:
        component_in_number:
          description: A number
          type: number
          default: 10.99
        component_in_path_1:
          description: A path
          type: path
        component_in_path_2:
          description: A path
          type: path

      outputs:
        component_out_path_1:
          type: path
        component_out_path_2:
          type: path

